yy/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#00210d",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "surface-container-high": "#eae8e5",
        "on-secondary-fixed-variant": "#584400",
        "tertiary-container": "#b91a20",
        "background": "#fbf9f6",
        "on-secondary-container": "#775e00",
        "outline": "#707a70",
        "on-secondary-fixed": "#241a00",
        "primary": "#005129",
        "on-secondary": "#ffffff",
        "on-background": "#1b1c1a",
        "outline-variant": "#bfc9be",
        "on-surface": "#1b1c1a",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#ffb3ac",
        "surface-container-highest": "#e4e2df",
        "primary-container": "#1a6b3c",
        "tertiary-fixed": "#ffdad6",
        "on-primary-fixed-variant": "#005229",
        "surface-container-low": "#f5f3f0",
        "inverse-primary": "#89d89e",
        "error-container": "#ffdad6",
        "secondary-container": "#fdd977",
        "error": "#ba1a1a",
        "surface-tint": "#1b6c3d",
        "on-tertiary-container": "#ffcbc6",
        "surface-variant": "#e4e2df",
        "tertiary": "#92000f",
        "surface-dim": "#dbdad7",
        "secondary-fixed": "#ffe08c",
        "secondary": "#745b00",
        "on-primary-container": "#9ae9ae",
        "surface-container": "#efeeeb",
        "surface-bright": "#fbf9f6",
        "on-surface-variant": "#404940",
        "primary-fixed-dim": "#89d89e",
        "secondary-fixed-dim": "#e5c363",
        "inverse-surface": "#30312f",
        "on-tertiary-fixed": "#410003",
        "on-tertiary-fixed-variant": "#930010",
        "surface": "#fbf9f6",
        "inverse-on-surface": "#f2f0ed",
        "primary-fixed": "#a5f4b8",
        "grade-sahih": "#16a34a",
        "grade-hasan": "#2563eb",
        "grade-daif": "#dc2626",
        'grade-fabricated': '#dc2626',
        'grade-unknown':    '#6b7280',
        // Dark mode colors (deep forest green)
        "dark-background": "#0a1f12",
        "dark-surface": "#0d2818",
        "dark-surface-container": "#12331f",
        "dark-surface-container-low": "#0d2818",
        "dark-surface-container-lowest": "#0a1f12",
        "dark-surface-container-high": "#1a3d26",
        "dark-surface-container-highest": "#254a31",
        "dark-primary": "#89d89e",
        "dark-primary-container": "#1a6b3c",
        "dark-on-primary": "#00210d",
        "dark-on-background": "#e2e3df",
        "dark-on-surface": "#e2e3df",
        "dark-on-surface-variant": "#c0c9c0",
        "dark-outline": "#8a938a",
        "dark-outline-variant": "#404940",
        "dark-secondary": "#e5c363",
        "dark-secondary-container": "#584400",
        "dark-on-primary-container": "#9ae9ae",
        "dark-on-secondary-container": "#fdd977",
        "dark-inverse-surface": "#e2e3df",
        "dark-inverse-on-surface": "#30312f",
        "dark-primary-fixed": "#a5f4b8",
        "dark-on-primary-fixed": "#00210d",
        "dark-surface-variant": "#404940",
        "dark-surface-dim": "#0a1f12",
        "dark-surface-bright": "#1a3d26",
        "dark-error": "#ffb4ab",
        "dark-error-container": "#93000a",
        // Dark grade colors (slightly lighter for dark mode readability)
        "dark-grade-sahih": "#22c55e",
        "dark-grade-hasan": "#3b82f6",
        "dark-grade-daif": "#ef4444",
        "dark-grade-fabricated": "#ef4444",
        "dark-grade-unknown": "#6b7280",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        "margin-desktop": "40px",
        gutter: "24px",
        "margin-mobile": "16px",
        "container-max-width": "1200px",
      },
      fontFamily: {
        "display-lg": ["Newsreader", "serif"],
        "ui-caption": ["Manrope", "sans-serif"],
        "ui-label": ["Manrope", "sans-serif"],
        "body-main": ["Newsreader", "serif"],
        "body-arabic": ["Amiri", "Noto Naskh Arabic", "Newsreader", "serif"],
        "h1-hadith": ["Newsreader", "serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.2", fontWeight: "600" }],
        "ui-caption": ["12px", { lineHeight: "1.4", fontWeight: "400" }],
        "ui-label": ["14px", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-main": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-arabic": ["28px", { lineHeight: "1.8", fontWeight: "400" }],
        "h1-hadith": ["32px", { lineHeight: "1.4", fontWeight: "500" }],
      },
      keyframes: {
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "spin-slow": {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(360deg)" },
        },
        "pulse-glow": {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(0, 81, 41, 0.2)" },
          "50%": { boxShadow: "0 0 0 8px rgba(0, 81, 41, 0)" },
        },
        "slide-in-left": {
          "0%": { transform: "translateX(-4px)", opacity: "0" },
          "100%": { transform: "translateX(0)", opacity: "1" },
        },
      },
      animation: {
        "fade-in-up": "fade-in-up 0.6s ease-out forwards",
        "fade-in": "fade-in 0.4s ease-out forwards",
        "spin-slow": "spin-slow 3s linear infinite",
        "pulse-glow": "pulse-glow 2s ease-in-out infinite",
        "slide-in-left": "slide-in-left 0.3s ease-out forwards",
      },
    },
  },
  plugins: [],
}
